### ISSUE TITLE
Option to hide console.log messages

### ISSUE THREAD

**Issue by williarin** [pressidium/pressidium-cookie-consent#42]
A nice feature would be to have a "Debug mode" option in the plugin that will show the `console.log` messages, and hide them all if the option is off. I think there shouldn't be any message in production mode.

**Comment by over-engineer** [comment]
Hey, @williarin!

Thank you for sharing your valuable feedback once more.

>I think there shouldn't be any message in production mode.

I totally agree with that. The issue was addressed in `1.3.0` (which was just relased on the Plugin Directory) by completely disabling the `console.log()`s.

Making it an option would require modifications to the underlying [`orestbida/cookieconsent`](https://github.com/orestbida/cookieconsent) library, which I’d prefer to avoid as it’d make updating the library unnecessarily complex.
