### ISSUE TITLE
Don't print cookie blocking script if there are no scripts to block

### ISSUE THREAD

**Issue by joppuyo** [pressidium/pressidium-cookie-consent#6]
Hello!

I am manually managing script blocking via setting parameters `type="text/plain"` and `data-cookiecategory="analytics"` and on analytics script tags. However, I noticed that the script `pressidium-cookie-consent/public/block-scripts.js` is still placed in the document head. Since this is a blocking script I'm a bit worried that it might have an effect on page loading performance.

I do understand that it needs to be a blocking script rather than an async one so it can manage other scripts on the page but I'm not sure if it needs to be loaded if there are no blocked scripts defined in the plugin admin page. Would it be possible to only place this script in the page head if there are blocked scripts defined?

Thanks!

**Comment by over-engineer** [comment]
Hey, @joppuyo!

Thank you for sharing your valuable feedback once more.

You’re absolutely right! The `/public/block-scripts.js` script is a render-blocking script and it’s best to avoid loading it when it’s not needed.

The issue was addressed in `1.0.3`, which was just released on the Plugin Directory.

**Comment by joppuyo** [comment]
Thank you for the fast response.
I updated the plugin and the script is now gone 🙂
