### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by mohammad425** [pressidium/pressidium-cookie-consent#8]
**Error:**
`Fatal error: Uncaught TypeError: Pressidium\WP\CookieConsent\Admin\Settings\Settings_Page::admin_footer_info(): Argument #1 ($content) must be of type string, null given, called in /var/www/vhosts/httpdocs/wordpress/wp-includes/class-wp-hook.php on line 308 and defined in /var/www/vhosts/httpdocs/wordpress/wp-content/plugins/pressidium-cookie-consent/includes/Admin/Settings/Settings_Page.php:183 Stack trace: #0 /var/www/vhosts/httpdocs/wordpress/wp-includes/class-wp-hook.php(308): Pressidium\WP\CookieConsent\Admin\Settings\Settings_Page->admin_footer_info(NULL) #1 /var/www/vhosts/httpdocs/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array) #2 /var/www/vhosts/httpdocs/wordpress/wp-admin/admin-footer.php(48): apply_filters('admin_footer_te...', '<span id="foote...') #3 /var/www/vhosts/httpdocs/wordpress/wp-admin/admin.php(297): require_once('/var/www/vhosts...') #4 {main} thrown in /var/www/vhosts/httpdocs/wordpress/wp-content/plugins/pressidium-cookie-consent/includes/Admin/Settings/Settings_Page.php on line 183`

**Plugin Version:** 1.0.3
**WordPress Version:** 6.2.2
**Server architecture:**	Linux 4.19.0-21-amd64 x86_64
**Web server:** Apache
**PHP version:** 8.2.7 (Supports 64bit values)

**Comment by over-engineer** [comment]
Hey, @mohammad425!

Thanks for taking the time to report this.

It looks like there was a conflict with a third-party plugin and/or theme that uses a `null` value for the [`admin_footer_text`](https://developer.wordpress.org/reference/hooks/admin_footer_text/) filter. That value should always be a `string`.

The issue should be fixed in `1.0.4`, which was just released [on the Plugin Directory](https://wordpress.org/plugins/pressidium-cookie-consent/).
